//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicTools.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PublicTools.Resources.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادمین ها نمی توانند فروشنده باشند.
        /// </summary>
        public static string Error_AdminsCanNotBeSellers {
            get {
                return ResourceManager.GetString("Error_AdminsCanNotBeSellers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا رمز عبور اشتباه است.
        /// </summary>
        public static string Error_AuthenticationFailed {
            get {
                return ResourceManager.GetString("Error_AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خریدار یافت نشد.
        /// </summary>
        public static string Error_BuyerNotFound {
            get {
                return ResourceManager.GetString("Error_BuyerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیرشاخه را نمی توان به عنوان والد انتخاب کرد.
        /// </summary>
        public static string Error_CannotSetProductCategoryChildsAsParent {
            get {
                return ResourceManager.GetString("Error_CannotSetProductCategoryChildsAsParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی انتخاب شده یافت نشد.
        /// </summary>
        public static string Error_CategoryNotFound {
            get {
                return ResourceManager.GetString("Error_CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات ناموفق.
        /// </summary>
        public static string Error_DeleteDataFailed {
            get {
                return ResourceManager.GetString("Error_DeleteDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در سفارش ، یک محصول بیش از یک بار تکرار شده است.
        /// </summary>
        public static string Error_DuplicateProductInAnOrder {
            get {
                return ResourceManager.GetString("Error_DuplicateProductInAnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئیات سفارش نمی تواند خالی باشد.
        /// </summary>
        public static string Error_EmptyOrderDetails {
            get {
                return ResourceManager.GetString("Error_EmptyOrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity not found.
        /// </summary>
        public static string Error_FindEntityFailed {
            get {
                return ResourceManager.GetString("Error_FindEntityFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات ناموفق.
        /// </summary>
        public static string Error_InsertDataFailed {
            get {
                return ResourceManager.GetString("Error_InsertDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به کاربران ادمین دسترسی ندارید.
        /// </summary>
        public static string Error_NoAccessToAdminUsers {
            get {
                return ResourceManager.GetString("Error_NoAccessToAdminUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد باید مقدار داشته باشد.
        /// </summary>
        public static string Error_NullInputCode {
            get {
                return ResourceManager.GetString("Error_NullInputCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آی دی باید مقدار داشته باشد.
        /// </summary>
        public static string Error_NullInputId {
            get {
                return ResourceManager.GetString("Error_NullInputId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدل وارد شده تهی است.
        /// </summary>
        public static string Error_NullInputModel {
            get {
                return ResourceManager.GetString("Error_NullInputModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئیات سفارش وارد شده تهی است.
        /// </summary>
        public static string Error_NullOrderDetail {
            get {
                return ResourceManager.GetString("Error_NullOrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش یافت نشد.
        /// </summary>
        public static string Error_OrderNotFound {
            get {
                return ResourceManager.GetString("Error_OrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شاخه والد یافت نشد.
        /// </summary>
        public static string Error_ParentCategoryNotFound {
            get {
                return ResourceManager.GetString("Error_ParentCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی دارای زیرشاخه است.
        /// </summary>
        public static string Error_ProductCategoryHasChild {
            get {
                return ResourceManager.GetString("Error_ProductCategoryHasChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی دارای محصول است.
        /// </summary>
        public static string Error_ProductCategoryHasProduct {
            get {
                return ResourceManager.GetString("Error_ProductCategoryHasProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آی دی شاخه و والد نمی تواند برابر باشد.
        /// </summary>
        public static string Error_ProductCategorySameIdandParentId {
            get {
                return ResourceManager.GetString("Error_ProductCategorySameIdandParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول یافت نشد.
        /// </summary>
        public static string Error_ProductNotFound {
            get {
                return ResourceManager.GetString("Error_ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شده تکراریست.
        /// </summary>
        public static string Error_RepetitiousCode {
            get {
                return ResourceManager.GetString("Error_RepetitiousCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد اجباریست.
        /// </summary>
        public static string Error_RequiredField {
            get {
                return ResourceManager.GetString("Error_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی دارای کاربر است.
        /// </summary>
        public static string Error_RoleIsGranted {
            get {
                return ResourceManager.GetString("Error_RoleIsGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی تکراریست.
        /// </summary>
        public static string Error_RoleNameAlreadyExist {
            get {
                return ResourceManager.GetString("Error_RoleNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی یافت نشد.
        /// </summary>
        public static string Error_RoleNotFound {
            get {
                return ResourceManager.GetString("Error_RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکلی در دریافت داده ها از پایگاه داده پیش آمده است.
        /// </summary>
        public static string Error_SelectAllFailed {
            get {
                return ResourceManager.GetString("Error_SelectAllFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروشنده یافت نشد.
        /// </summary>
        public static string Error_SellerNotFound {
            get {
                return ResourceManager.GetString("Error_SellerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان انجام این عملیات محدود به داده های مربوط به کاربر احراز هویت شده می باشد.
        /// </summary>
        public static string Error_UnauthorizedOwner {
            get {
                return ResourceManager.GetString("Error_UnauthorizedOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات ناموفق.
        /// </summary>
        public static string Error_UpdateDataFailed {
            get {
                return ResourceManager.GetString("Error_UpdateDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل تکراریست.
        /// </summary>
        public static string Error_UserCellPhoneAlreadyExist {
            get {
                return ResourceManager.GetString("Error_UserCellPhoneAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل تکراریست.
        /// </summary>
        public static string Error_UserEmailAlreadyExist {
            get {
                return ResourceManager.GetString("Error_UserEmailAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر ادمین اصلی است.
        /// </summary>
        public static string Error_UserIsGodAdmin {
            get {
                return ResourceManager.GetString("Error_UserIsGodAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروشنده دارای سفارش است.
        /// </summary>
        public static string Error_UserIsSellerWithOrder {
            get {
                return ResourceManager.GetString("Error_UserIsSellerWithOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری تکراریست.
        /// </summary>
        public static string Error_UserNameAlreadyExist {
            get {
                return ResourceManager.GetString("Error_UserNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدملی تکراریست.
        /// </summary>
        public static string Error_UserNationalIdAlreadyExist {
            get {
                return ResourceManager.GetString("Error_UserNationalIdAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی تایید شده قابل تغییر نیست.
        /// </summary>
        public static string Error_UserNationalIdIsConfirmed {
            get {
                return ResourceManager.GetString("Error_UserNationalIdIsConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر یافت نشد.
        /// </summary>
        public static string Error_UserNotFound {
            get {
                return ResourceManager.GetString("Error_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خریدار اشتباه است.
        /// </summary>
        public static string Error_WrongBuyer {
            get {
                return ResourceManager.GetString("Error_WrongBuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی وارد شده صحیح نیست.
        /// </summary>
        public static string Error_WrongProductCategory {
            get {
                return ResourceManager.GetString("Error_WrongProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروشنده اشتباه است.
        /// </summary>
        public static string Error_WrongSeller {
            get {
                return ResourceManager.GetString("Error_WrongSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار نمی تواند صفر یا کمتر باشد.
        /// </summary>
        public static string Error_ZeroOrLessQuantity {
            get {
                return ResourceManager.GetString("Error_ZeroOrLessQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت واحد نمی تواند صفر یا کمتر باشد.
        /// </summary>
        public static string Error_ZeroOrLessUnitPrice {
            get {
                return ResourceManager.GetString("Error_ZeroOrLessUnitPrice", resourceCulture);
            }
        }
    }
}
