//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicTools.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PublicTools.Resources.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuyerNotFound.
        /// </summary>
        public static string Error_BuyerNotFound {
            get {
                return ResourceManager.GetString("Error_BuyerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected product category does not exist.
        /// </summary>
        public static string Error_CategoryNotFound {
            get {
                return ResourceManager.GetString("Error_CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed.
        /// </summary>
        public static string Error_DeleteDataFailed {
            get {
                return ResourceManager.GetString("Error_DeleteDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of products are duplicate in an order.
        /// </summary>
        public static string Error_DuplicateProductInAnOrder {
            get {
                return ResourceManager.GetString("Error_DuplicateProductInAnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderDetails can not be empty.
        /// </summary>
        public static string Error_EmptyOrderDetails {
            get {
                return ResourceManager.GetString("Error_EmptyOrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity not found.
        /// </summary>
        public static string Error_FindEntityFailed {
            get {
                return ResourceManager.GetString("Error_FindEntityFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed.
        /// </summary>
        public static string Error_InsertDataFailed {
            get {
                return ResourceManager.GetString("Error_InsertDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Code is null.
        /// </summary>
        public static string Error_NullInputCode {
            get {
                return ResourceManager.GetString("Error_NullInputCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Id is null.
        /// </summary>
        public static string Error_NullInputId {
            get {
                return ResourceManager.GetString("Error_NullInputId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input model is null.
        /// </summary>
        public static string Error_NullInputModel {
            get {
                return ResourceManager.GetString("Error_NullInputModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderDetail can not be null.
        /// </summary>
        public static string Error_NullOrderDetail {
            get {
                return ResourceManager.GetString("Error_NullOrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order not found.
        /// </summary>
        public static string Error_OrderNotFound {
            get {
                return ResourceManager.GetString("Error_OrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected parent does not exist.
        /// </summary>
        public static string Error_ParentCategoryNotFound {
            get {
                return ResourceManager.GetString("Error_ParentCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ProductCategory has child.
        /// </summary>
        public static string Error_ProductCategoryHasChild {
            get {
                return ResourceManager.GetString("Error_ProductCategoryHasChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product category has products.
        /// </summary>
        public static string Error_ProductCategoryHasProduct {
            get {
                return ResourceManager.GetString("Error_ProductCategoryHasProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id and ParentId can not be same.
        /// </summary>
        public static string Error_ProductCategorySameIdandParentId {
            get {
                return ResourceManager.GetString("Error_ProductCategorySameIdandParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found.
        /// </summary>
        public static string Error_ProductNotFound {
            get {
                return ResourceManager.GetString("Error_ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered code already exists.
        /// </summary>
        public static string Error_RepetitiousCode {
            get {
                return ResourceManager.GetString("Error_RepetitiousCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is required.
        /// </summary>
        public static string Error_RequiredField {
            get {
                return ResourceManager.GetString("Error_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem in fetching data from database.
        /// </summary>
        public static string Error_SelectAllFailed {
            get {
                return ResourceManager.GetString("Error_SelectAllFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller not found.
        /// </summary>
        public static string Error_SellerNotFound {
            get {
                return ResourceManager.GetString("Error_SellerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed.
        /// </summary>
        public static string Error_UpdateDataFailed {
            get {
                return ResourceManager.GetString("Error_UpdateDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong buyer.
        /// </summary>
        public static string Error_WrongBuyer {
            get {
                return ResourceManager.GetString("Error_WrongBuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong seller.
        /// </summary>
        public static string Error_WrongSeller {
            get {
                return ResourceManager.GetString("Error_WrongSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity can not be 0 or less.
        /// </summary>
        public static string Error_ZeroOrLessQuantity {
            get {
                return ResourceManager.GetString("Error_ZeroOrLessQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitPrice can not be 0 or less.
        /// </summary>
        public static string Error_ZeroOrLessUnitPrice {
            get {
                return ResourceManager.GetString("Error_ZeroOrLessUnitPrice", resourceCulture);
            }
        }
    }
}
